# Generated by Django 6.0.3 on 2026-03-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderaddress',
            options={'verbose_name_plural': 'order_addresses'},
        ),
    ]
